language: node_js

node_js:
  - '6'

before_script:
  - npm run-script prepublish

notifications:
  email: false

addons:
  browserstack:
    username: "jrmylal2"
    access_key:
      secure: "VDNlTyC21fSHHIIcm2NCDwKIZH/ZB02jIFD+pd2zkXM9im8eHzz2znJGLV7kmTgPrbbIJh6lCLrxUKLhPazMqV3P7GIaDxzvU8/FDWJ1XiYrShlelwOtiS1/p75fxwF63ZdWJKE6yrYPi2KEl30Jbxdq2OSDrIYRzUp2hLp8rm9+sqWEHhCSrHJtCfMfy5KnQnmSBBEvYxcQ5Ni8+X6AGYAmNs3G2ydLNHi/lncgNQLt0EAD08lQ0iASUneq8Ule+BaGyF9jzTXR9ZWuD9zPXoCzdbW8fo/SdgtAxdIJ9GdItgCIMG4ra6xDBqkkeNRQZG4j2Kz7QoMgkRk4ImJAF/XkH0Iy9PCYQ8ECzT4aiivMUhZCwKEFX5vWYNYzilTo9UbWjkUyDlWAnzOWIA/AEX5zP0kB4PWc0AcmGo59MVOQkvgOSlnNb3Atfs/oHHf2LBA45/lat69pOIBFvBlBwBB6YPXPAHIzB6pBAv8wfcElaElL5IqP6FaMvzebZP6FLUOIlXS3Peqblmz+FkN7cCwCOtVOW5DwzZVAL6RtSQeUPd7kbBWNq45Omnevs+q4vPCQU1SqX6dcN8zlT79hsXUOjm74eWOsp8E84//NQdNWHmGpIQ2NjJtD7DmzIlsqN3LoKnoqAsx650jgSdXZftYAEJQVb5JqolJmC/gvWm4="

# use https://www.browserstack.com/automate/node#setting-os-and-browser
env:
  - WEBDRIVER_BROWSER_NAME="chrome"
  - WEBDRIVER_BROWSER_NAME="internet explorer" WEBDRIVER_BROWSER_VERSION="10"
  - WEBDRIVER_BROWSER_NAME="internet explorer" WEBDRIVER_BROWSER_VERSION="11"
  - WEBDRIVER_BROWSER_NAME="MicrosoftEdge" WEBDRIVER_BROWSER_VERSION="13"
  - WEBDRIVER_BROWSER_NAME="MicrosoftEdge" WEBDRIVER_BROWSER_VERSION="14"
  - WEBDRIVER_BROWSER_NAME="firefox"
  - WEBDRIVER_BROWSER_NAME="safari"
  - WEBDRIVER_BROWSER_NAME="android" WEBDRIVER_DEVICE="Samsung Galaxy S5" WEBDRIVER_PLATFORM="ANDROID"
  - WEBDRIVER_BROWSER_NAME=="iPhone" WEBDRIVER_DEVICE="iPhone 5" WEBDRIVER_PLATFORM="MAC"
