language: node_js

node_js:
  - '6'

before_script:
  - npm run-script prepublish

notifications:
  email: false

addons:
  browserstack:
    username: "edasarl1"
    access_key:
      secure: "s7iCj8pd2z8+qjApuyQUStHS31vmuTL6uoOzG18O2Tr2wK0q+4XINWzy6xWNrWkKo1StoK6TW4KPcnNJKSciZJnd/wie+tj6aDooX1h1DX65Jx4Mx6jtK/u02ZD8XXUf9QSCDiOJKXtYt2/gnDbGfnbsGSBcCkCKuhYzuMf5DZHdm6ja5n3I0hOsCmeGnHGlySJ1wxqDKyIL1hrP7DuxhNCryPUHGf0/Yn8P7t6wj+lY6EhGa2b0oUQCdqu58vR/jSBEbSGimU/FT43E2OKLNx5uEMl1bWa09neGrkLERZPe45XBIPhGsPpI2VPLXwNrV821ZTaV9UbXarZdcF2Zdiw9HJNNv3zPiDFrgw+QJhFEZKcgjandjlVhtRU1wLZ8tKJKaW7TOmMiDK0AX4LCrqorJkUqkHzlzAXBcosVjzt4jROvHdhbIOYaFodGM12iyD7iKTDnnMd/EMw8rnbP2JI4+IzN3q9OQ/xuTDf2ow7wt3UnHBb67h2XdpbD1BnRPJtyI1G6WQUWM1iqoXZ9+ItuRfcq/ekSsia6qvrp6MaVHL5v0ozPm4mXS3L9jE9QFTfFZjPzH5x+3zi/O9Y8y2xwKuNwhWTdZnmSaaRmAMvMSWV+O/9UWfV/PFpTyncGoUGwGgiqkpAH0zMXfInYDHw2u68nhrKNDWYF4tKZuWs="

# use https://www.browserstack.com/automate/node#setting-os-and-browser
env:
  - WEBDRIVER_BROWSER_NAME="chrome"
  - WEBDRIVER_BROWSER_NAME="internet explorer" WEBDRIVER_BROWSER_VERSION="10"
  - WEBDRIVER_BROWSER_NAME="internet explorer" WEBDRIVER_BROWSER_VERSION="11"
  - WEBDRIVER_BROWSER_NAME="MicrosoftEdge" WEBDRIVER_BROWSER_VERSION="13"
  - WEBDRIVER_BROWSER_NAME="firefox"
  - WEBDRIVER_BROWSER_NAME="safari"
  - WEBDRIVER_BROWSER_NAME="android" WEBDRIVER_DEVICE="Samsung Galaxy S5" WEBDRIVER_PLATFORM="ANDROID"
