language: node_js

node_js:
  - '6'

before_script:
  - npm run-script prepublish

notifications:
  email: false

addons:
  browserstack:
    username: "jrmylal2"
    access_key:
      secure: "VDNlTyC21fSHHIIcm2NCDwKIZH/ZB02jIFD+pd2zkXM9im8eHzz2znJGLV7kmTgPrbbIJh6lCLrxUKLhPazMqV3P7GIaDxzvU8/FDWJ1XiYrShlelwOtiS1/p75fxwF63ZdWJKE6yrYPi2KEl30Jbxdq2OSDrIYRzUp2hLp8rm9+sqWEHhCSrHJtCfMfy5KnQnmSBBEvYxcQ5Ni8+X6AGYAmNs3G2ydLNHi/lncgNQLt0EAD08lQ0iASUneq8Ule+BaGyF9jzTXR9ZWuD9zPXoCzdbW8fo/SdgtAxdIJ9GdItgCIMG4ra6xDBqkkeNRQZG4j2Kz7QoMgkRk4ImJAF/XkH0Iy9PCYQ8ECzT4aiivMUhZCwKEFX5vWYNYzilTo9UbWjkUyDlWAnzOWIA/AEX5zP0kB4PWc0AcmGo59MVOQkvgOSlnNb3Atfs/oHHf2LBA45/lat69pOIBFvBlBwBB6YPXPAHIzB6pBAv8wfcElaElL5IqP6FaMvzebZP6FLUOIlXS3Peqblmz+FkN7cCwCOtVOW5DwzZVAL6RtSQeUPd7kbBWNq45Omnevs+q4vPCQU1SqX6dcN8zlT79hsXUOjm74eWOsp8E84//NQdNWHmGpIQ2NjJtD7DmzIlsqN3LoKnoqAsx650jgSdXZftYAEJQVb5JqolJmC/gvWm4="

# use https://www.browserstack.com/automate/node#setting-os-and-browser
env:
  - WEBDRIVER="browserName:'Chrome'"
  - WEBDRIVER="browserName:'IE', browser_version:'10.0', os:'Windows', os_version:'7'"
  - WEBDRIVER="browserName:'IE', browser_version:'11.0', os:'Windows', os_version:'7'"
  - WEBDRIVER="browserName:'IE', browser_version:'10.0', os:'Windows', os_version:'8'"
  - WEBDRIVER="browserName:'Edge', browser_version:'13.0', os:'Windows', os_version:'10'"
  - WEBDRIVER="browserName:'Edge', browser_version:'14.0', os:'Windows', os_version:'10'"
  - WEBDRIVER="browserName:'iPhone', device:'iPhone 5', platform:'MAC'"
  - WEBDRIVER="browserName:'iPhone', device:'iPhone 6', platform:'MAC'"
  - WEBDRIVER="browserName:'android', device:'Samsung Galaxy S5', platform:'ANDROID'"
  - WEBDRIVER="browserName:'Firefox'"
  - WEBDRIVER="browserName:'Safari'"
