language: node_js

node_js:
  - '6'

before_script:
  - npm run-script prepublish

notifications:
  email: false

addons:
  browserstack: true

env:
  - WEBDRIVER_BROWSER_NAME="chrome"
  - WEBDRIVER_BROWSER_NAME="internet explorer" WEBDRIVER_BROWSER_VERSION="10"
  - WEBDRIVER_BROWSER_NAME="internet explorer" WEBDRIVER_BROWSER_VERSION="11"
  - WEBDRIVER_BROWSER_NAME="MicrosoftEdge" WEBDRIVER_BROWSER_VERSION="13"
  - WEBDRIVER_BROWSER_NAME="firefox"
  - WEBDRIVER_BROWSER_NAME="safari"
  - WEBDRIVER_BROWSER_NAME="android"
